name: VylariaAPI
author: GeekLegend
version: 1.0
main: fr.vylaria.api.VylariaAPI
commands:
  rank:
    aliases:
      - "grades"
  host:
    aliases:
      - "h"
  coins:
    aliases:
      - "jetons"
  eur:
    aliases:
      - "euros"
  mod:
    aliases:
      - "modo"
  ss:
    description: "ban"